In [2]:
import numpy as np

#crera un arreglo de NumPy
arreglo = np.array([1, 2, 3, 4, 5])
arreglo

array([1, 2, 3, 4, 5])

In [3]:
#multiplicar todos los elementos por 2
multiplicado = arreglo * 2
multiplicado

array([ 2,  4,  6,  8, 10])

In [4]:
#sumar 3 a cada elemento
sumado = arreglo + 3
sumado

array([4, 5, 6, 7, 8])

In [5]:
#calcular la media del arreglo
media = np.mean(arreglo)
media

3.0